// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Role struct {
	RoleID string `json:"roleId" db:"role_id"`
}

type RoleInput struct {
	RoleID string `json:"roleId"`
	Role   string `json:"role"`
}
