package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"encoding/base64"
	"fmt"
	"strconv"

	"github.com/ardihikaru/graphql-example-part-1/pkg/graph/user/generated"
	"github.com/ardihikaru/graphql-example-part-1/pkg/graph/user/model"
	"github.com/ardihikaru/graphql-example-part-1/pkg/middleware"
	"github.com/ardihikaru/graphql-example-part-1/pkg/service/session"
)

// UserLogin generates a token based on the provided credential
func (r *mutationResolver) UserLogin(ctx context.Context, userName string, password string) (*model.TokenResponse, error) {
	correct, err := r.Authenticate(userName, password)
	if !correct {
		return nil, err
	}

	userId, err := r.GetUserIdByUsername(userName)
	if err != nil {
		return nil, err
	}

	//authorizerSvc := auth.NewService(r.Log, r.Cfg.JwtAuth.ExpiredInSec, r.TokenAuth)
	token, err := r.utility.Authorize(userId, userName)
	if err != nil {
		return nil, err
	}

	return &model.TokenResponse{
		UserID:  strconv.Itoa(userId),
		Token:   token.AccessToken,
		Expired: int(token.ExpiredIn),
	}, nil
}

// UserCreate creates a new user
func (r *mutationResolver) UserCreate(ctx context.Context, data model.UserInput) (*model.User, error) {
	// extracts session from the context
	sessionData := ctx.Value(middleware.SessionKey).(session.Session)

	resp, err := r.Create(data, &sessionData.UserId)
	return resp, err
}

// UserUpdate is the resolver for the userUpdate field.
func (r *mutationResolver) UserUpdate(ctx context.Context, data model.UserInput) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: UserUpdate - userUpdate"))
}

// PasswordEncrypt encrypts the provided password
func (r *mutationResolver) PasswordEncrypt(ctx context.Context, password string) (string, error) {
	passwordEncrypted, err := r.EncryptPassword(password, r.cfg.Encryption.PublicKeyRSA)
	return base64.StdEncoding.EncodeToString(passwordEncrypted), err
}

// UserGet fetches a user data
func (r *queryResolver) UserGet(ctx context.Context, userID *string) (*model.User, error) {
	var setUserId int64
	if userID != nil {
		setUserId, _ = strconv.ParseInt(*userID, 10, 64)
	}

	return r.GetById(setUserId)
}

// UserList fetches list of user
func (r *queryResolver) UserList(ctx context.Context, userID string, statusCd string) ([]*model.User, error) {
	return r.List(userID, statusCd)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
