// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Role struct {
	RoleID string `json:"roleId" db:"role_id"`
}

type TokenResponse struct {
	UserID  string `json:"userId"`
	Token   string `json:"token"`
	Expired int    `json:"expired"`
}

type User struct {
	UserID   string `json:"userId" db:"user_id"`
	UserNm   string `json:"userNm" db:"user_nm"`
	IsAdmin  int    `json:"isAdmin" db:"is_admin"`
	StatusCd string `json:"statusCd" db:"status_cd"`
}

type UserInput struct {
	UserID   string `json:"userId"`
	UserNm   string `json:"userNm"`
	IsAdmin  int    `json:"isAdmin"`
	StatusCd string `json:"statusCd"`
	PassHash string `json:"passHash"`
}
