package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/ardihikaru/graphql-example-part-1/internal/graph/generated"
	"github.com/ardihikaru/graphql-example-part-1/internal/graph/model"
)

// RoleGet is the resolver for the roleGet field.
func (r *queryResolver) RoleGet(ctx context.Context, roleID *string) (*model.Role, error) {
	return &model.Role{
		RoleID: "123",
	}, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
